apiVersion: v1
kind: ConfigMap
metadata:
  name: book-gateway-config
data:
  SERVER_PORT: '8080'
  USER_SERVICE_NAME: 'user-service'
  USER_SERVICE_PORT: '8081'
  BOOK_SERVICE_NAME: 'book-service'
  BOOK_SERVICE_PORT:  '8082'
  ORDER_SERVICE_NAME: 'order-service'
  ORDER_SERVICE_PORT: '8083'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-gateway
  template:
    metadata:
      labels:
        app: book-gateway
    spec:
      containers:
      - name: gateway
        image: huynhngochuyhoang/book-gateway
        envFrom:
          - configMapRef:
              name: book-gateway-config
        livenessProbe:
          httpGet:
            path: "/actuator/health/liveness"
            port: 8080
          failureThreshold: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: "/actuator/health/readiness"
            port: 8080
          failureThreshold: 3
          periodSeconds: 3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: book-gateway
spec:
  selector:
    app: book-gateway
  ports:
  - port: 8080
    targetPort: 8080
